//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersExam
    {
        public int UsersExamId { get; set; }
        public int UserId { get; set; }
        public int ExamId { get; set; }
        public int QuizPoint { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual User User { get; set; }
    }
}
